<?php

namespace app\modules\admin\controllers;

use app\assets\AdminAsset;
use app\models\Articles;
use app\models\ArticlesOption;
use app\models\CityList;
use app\models\Favicon;
use app\models\FooterHeaderParam;
use app\models\FooterHeaderParamLang;
use yii;
use app\models\Heading;
use app\models\LanguageSetting;
use app\models\MainOption;
use app\models\Pages;
use app\models\SiteSetting;
use Faker\Provider\Lorem;
use yii\web\Controller;
use yii\web\UploadedFile;

/**
 * Default controller for the `admin` module
 */
class QutController extends MainController
{
  public $array = ".sui-glass
  .sui-music
  .sui-search
  .sui-envelope-o
  .sui-heart
  .sui-star
  .sui-star-o
  .sui-user
  .sui-film
  .sui-th-large
  .sui-th
  .sui-th-list
  .sui-check
  .sui-close
  .sui-remove
  .sui-times
  .sui-search-plus
  .sui-search-minus
  .sui-power-off
  .sui-signal
  .sui-cog
  .sui-gear
  .sui-trash-o
  .sui-home
  .sui-file-o
  .sui-clock-o
  .sui-road
  .sui-download
  .sui-arrow-circle-o-down
  .sui-arrow-circle-o-up
  .sui-inbox
  .sui-play-circle-o
  .sui-repeat
  .sui-rotate-right
  .sui-refresh
  .sui-list-alt
  .sui-lock
  .sui-flag
  .sui-headphones
  .sui-volume-off
  .sui-volume-down
  .sui-volume-up
  .sui-qrcode
  .sui-barcode
  .sui-tag
  .sui-tags
  .sui-book
  .sui-bookmark
  .sui-print
  .sui-camera
  .sui-font
  .sui-bold
  .sui-italic
  .sui-text-height
  .sui-text-width
  .sui-align-left
  .sui-align-center
  .sui-align-right
  .sui-align-justify
  .sui-list
  .sui-dedent
  .sui-outdent
  .sui-indent
  .sui-video-camera
  .sui-image
  .sui-photo
  .sui-picture-o
  .sui-pencil
  .sui-map-marker
  .sui-adjust
  .sui-tint
  .sui-edit
  .sui-pencil-square-o
  .sui-share-square-o
  .sui-check-square-o
  .sui-arrows
  .sui-step-backward
  .sui-fast-backward
  .sui-backward
  .sui-play
  .sui-pause
  .sui-stop
  .sui-forward
  .sui-fast-forward
  .sui-step-forward
  .sui-eject
  .sui-chevron-left
  .sui-chevron-right
  .sui-plus-circle
  .sui-minus-circle
  .sui-times-circle
  .sui-check-circle
  .sui-question-circle
  .sui-info-circle
  .sui-crosshairs
  .sui-times-circle-o
  .sui-check-circle-o
  .sui-ban
  .sui-arrow-left
  .sui-arrow-right
  .sui-arrow-up
  .sui-arrow-down
  .sui-mail-forward
  .sui-share
  .sui-expand
  .sui-compress
  .sui-plus
  .sui-minus
  .sui-asterisk
  .sui-exclamation-circle
  .sui-gift
  .sui-leaf
  .sui-fire
  .sui-eye
  .sui-eye-slash
  .sui-exclamation-triangle
  .sui-warning
  .sui-plane
  .sui-calendar
  .sui-random
  .sui-comment
  .sui-magnet
  .sui-chevron-up
  .sui-chevron-down
  .sui-retweet
  .sui-shopping-cart
  .sui-folder
  .sui-folder-open
  .sui-arrows-v
  .sui-arrows-h
  .sui-bar-chart-o.sui-bar-chart
  .sui-twitter-square
  .sui-facebook-square
  .sui-camera-retro
  .sui-key
  .sui-cogs.sui-gears
  .sui-comments
  .sui-thumbs-o-up
  .sui-thumbs-o-down
  .sui-star-half
  .sui-heart-o
  .sui-sign-out
  .sui-linkedin-square
  .sui-thumb-tack
  .sui-external-link
  .sui-sign-in
  .sui-trophy
  .sui-github-square
  .sui-upload
  .sui-lemon-o
  .sui-phone
  .sui-square-o
  .sui-bookmark-o
  .sui-phone-square
  .sui-twitter
  .sui-facebook-f.sui-facebook
  .sui-github
  .sui-unlock
  .sui-credit-card
  .sui-feed.sui-rss
  .sui-hdd-o
  .sui-bullhorn
  .sui-bell
  .sui-certificate
  .sui-hand-o-right
  .sui-hand-o-left
  .sui-hand-o-up
  .sui-hand-o-down
  .sui-arrow-circle-left
  .sui-arrow-circle-right
  .sui-arrow-circle-up
  .sui-arrow-circle-down
  .sui-globe
  .sui-globe-e
  .sui-globe-w
  .sui-wrench
  .sui-tasks
  .sui-filter
  .sui-briefcase
  .sui-arrows-alt
  .sui-community.sui-group.sui-users
  .sui-chain.sui-link
  .sui-cloud
  .sui-flask
  .sui-cut.sui-scissors
  .sui-copy.sui-files-o
  .sui-paperclip
  .sui-floppy-o.sui-save
  .sui-square
  .sui-bars.sui-navicon.sui-reorder
  .sui-list-ul
  .sui-list-ol
  .sui-strikethrough
  .sui-underline
  .sui-table
  .sui-magic
  .sui-truck
  .sui-pinterest
  .sui-pinterest-square
  .sui-google-plus-square
  .sui-google-plus
  .sui-money
  .sui-caret-down
  .sui-caret-up
  .sui-caret-left
  .sui-caret-right
  .sui-columns
  .sui-sort.sui-unsorted
  .sui-sort-desc.sui-sort-down
  .sui-sort-asc.sui-sort-up
  .sui-envelope
  .sui-linkedin
  .sui-rotate-left.sui-undo
  .sui-gavel.sui-legal
  .sui-dashboard.sui-tachometer
  .sui-comment-o
  .sui-comments-o
  .sui-bolt.sui-flash
  .sui-sitemap
  .sui-umbrella
  .sui-clipboard.sui-paste
  .sui-lightbulb-o
  .sui-exchange
  .sui-cloud-download
  .sui-cloud-upload
  .sui-user-md
  .sui-stethoscope
  .sui-suitcase
  .sui-bell-o
  .sui-coffee
  .sui-cutlery
  .sui-file-text-o
  .sui-building-o
  .sui-hospital-o
  .sui-ambulance
  .sui-medkit
  .sui-fighter-jet
  .sui-beer
  .sui-h-square
  .sui-plus-square
  .sui-angle-double-left
  .sui-angle-double-right
  .sui-angle-double-up
  .sui-angle-double-down
  .sui-angle-left
  .sui-angle-right
  .sui-angle-up
  .sui-angle-down
  .sui-desktop
  .sui-laptop
  .sui-tablet
  .sui-mobile-phone.sui-mobile
  .sui-circle-o
  .sui-quote-left
  .sui-quote-right
  .sui-spinner
  .sui-circle
  .sui-mail-reply.sui-reply
  .sui-github-alt
  .sui-folder-o
  .sui-folder-open-o
  .sui-smile-o
  .sui-frown-o
  .sui-meh-o
  .sui-keyboard-o
  .sui-flag-o
  .sui-flag-checkered
  .sui-terminal
  .sui-code
  .sui-mail-reply-all.sui-reply-all
  .sui-star-half-empty.sui-star-half-full.sui-star-half-o
  .sui-location-arrow
  .sui-crop
  .sui-code-fork
  .sui-chain-broken.sui-unlink
  .sui-question
  .sui-info
  .sui-exclamation
  .sui-superscript
  .sui-subscript
  .sui-eraser
  .sui-puzzle-piece
  .sui-microphone
  .sui-microphone-slash
  .sui-shield
  .sui-calendar-o
  .sui-fire-extinguisher
  .sui-rocket
  .sui-maxcdn
  .sui-chevron-circle-left
  .sui-chevron-circle-right
  .sui-chevron-circle-up
  .sui-chevron-circle-down
  .sui-html5
  .sui-css3
  .sui-anchor
  .sui-unlock-alt
  .sui-bullseye
  .sui-ellipsis-h
  .sui-ellipsis-v
  .sui-rss-square
  .sui-play-circle
  .sui-ticket
  .sui-minus-square
  .sui-minus-square-o
  .sui-level-up
  .sui-level-down
  .sui-check-square
  .sui-pencil-square
  .sui-external-link-square
  .sui-share-square
  .sui-compass
  .sui-caret-square-o-down.sui-toggle-down
  .sui-caret-square-o-up.sui-toggle-up
  .sui-caret-square-o-right.sui-toggle-right
  .sui-eur.sui-euro
  .sui-gbp
  .sui-dollar.sui-usd
  .sui-inr.sui-rupee
  .sui-cny.sui-jpy.sui-rmb.sui-yen
  .sui-rouble.sui-rub.sui-ruble
  .sui-krw.sui-won
  .sui-bitcoin.sui-btc
  .sui-file
  .sui-file-text
  .sui-sort-alpha-asc
  .sui-sort-alpha-desc
  .sui-sort-amount-asc
  .sui-sort-amount-desc
  .sui-sort-numeric-asc
  .sui-sort-numeric-desc
  .sui-thumbs-up
  .sui-thumbs-down
  .sui-youtube-square
  .sui-youtube
  .sui-xing
  .sui-xing-square
  .sui-youtube-play
  .sui-dropbox
  .sui-stack-overflow
  .sui-instagram
  .sui-flickr
  .sui-adn
  .sui-bitbucket
  .sui-bitbucket-square
  .sui-tumblr
  .sui-tumblr-square
  .sui-long-arrow-down
  .sui-long-arrow-up
  .sui-long-arrow-left
  .sui-long-arrow-right
  .sui-apple
  .sui-windows
  .sui-android
  .sui-linux
  .sui-dribbble
  .sui-skype
  .sui-foursquare
  .sui-trello
  .sui-female
  .sui-male
  .sui-gittip.sui-gratipay
  .sui-sun-o
  .sui-moon-o
  .sui-archive
  .sui-bug
  .sui-vk
  .sui-weibo
  .sui-renren
  .sui-pagelines
  .sui-stack-exchange
  .sui-arrow-circle-o-right
  .sui-arrow-circle-o-left
  .sui-caret-square-o-left.sui-toggle-left
  .sui-dot-circle-o
  .sui-wheelchair
  .sui-vimeo-square
  .sui-try.sui-turkish-lira
  .sui-plus-square-o
  .sui-space-shuttle
  .sui-slack
  .sui-envelope-square
  .sui-wordpress
  .sui-openid
  .sui-bank.sui-institution.sui-university
  .sui-graduation-cap.sui-mortar-board
  .sui-yahoo
  .sui-google
  .sui-reddit
  .sui-reddit-square
  .sui-stumbleupon-circle
  .sui-stumbleupon
  .sui-delicious
  .sui-digg
  .sui-drupal
  .sui-joomla
  .sui-language
  .sui-fax
  .sui-building
  .sui-child
  .sui-paw
  .sui-spoon
  .sui-cube
  .sui-cubes
  .sui-behance
  .sui-behance-square
  .sui-steam
  .sui-steam-square
  .sui-recycle
  .sui-automobile.sui-car
  .sui-cab.sui-taxi
  .sui-tree
  .sui-spotify
  .sui-deviantart
  .sui-soundcloud
  .sui-database
  .sui-file-pdf-o
  .sui-file-word-o
  .sui-file-excel-o
  .sui-file-powerpoint-o
  .sui-file-image-o.sui-file-photo-o.sui-file-picture-o
  .sui-file-archive-o.sui-file-zip-o
  .sui-file-audio-o.sui-file-sound-o
  .sui-file-movie-o.sui-file-video-o
  .sui-file-code-o
  .sui-vine
  .sui-codepen
  .sui-jsfiddle
  .sui-life-bouy.sui-life-buoy.sui-life-ring.sui-life-saver.sui-support
  .sui-circle-o-notch
  .sui-ra.sui-rebel.sui-resistance
  .sui-empire.sui-ge
  .sui-git-square
  .sui-git
  .sui-hacker-news.sui-y-combinator-square.sui-yc-square
  .sui-tencent-weibo
  .sui-qq
  .sui-wechat.sui-weixin
  .sui-paper-plane.sui-send
  .sui-paper-plane-o.sui-send-o
  .sui-history
  .sui-circle-thin
  .sui-header
  .sui-paragraph
  .sui-sliders
  .sui-share-alt
  .sui-share-alt-square
  .sui-bomb
  .sui-futbol-o.sui-soccer-ball-o
  .sui-tty
  .sui-binoculars
  .sui-plug
  .sui-slideshare
  .sui-twitch
  .sui-yelp
  .sui-newspaper-o
  .sui-wifi
  .sui-calculator
  .sui-paypal
  .sui-google-wallet
  .sui-cc-visa
  .sui-cc-mastercard
  .sui-cc-discover
  .sui-cc-amex
  .sui-cc-paypal
  .sui-cc-stripe
  .sui-bell-slash
  .sui-bell-slash-o
  .sui-trash
  .sui-copyright
  .sui-at
  .sui-eyedropper
  .sui-paint-brush
  .sui-birthday-cake
  .sui-area-chart
  .sui-pie-chart
  .sui-line-chart
  .sui-lastfm
  .sui-lastfm-square
  .sui-toggle-off
  .sui-toggle-on
  .sui-bicycle
  .sui-bus
  .sui-ioxhost
  .sui-angellist
  .sui-cc
  .sui-ils.sui-shekel.sui-sheqel
  .sui-meanpath
  .sui-buysellads
  .sui-connectdevelop
  .sui-dashcube
  .sui-forumbee
  .sui-leanpub
  .sui-sellsy
  .sui-shirtsinbulk
  .sui-simplybuilt
  .sui-skyatlas
  .sui-cart-plus
  .sui-cart-arrow-down
  .sui-diamond
  .sui-ship
  .sui-user-secret
  .sui-motorcycle
  .sui-street-view
  .sui-heartbeat
  .sui-venus
  .sui-mars
  .sui-mercury
  .sui-intersex.sui-transgender
  .sui-transgender-alt
  .sui-venus-double
  .sui-mars-double
  .sui-venus-mars
  .sui-mars-stroke
  .sui-mars-stroke-v
  .sui-mars-stroke-h
  .sui-neuter
  .sui-genderless
  .sui-facebook-official
  .sui-pinterest-p
  .sui-whatsapp
  .sui-server
  .sui-user-plus
  .sui-user-times
  .sui-bed.sui-hotel
  .sui-viacoin
  .sui-train
  .sui-subway
  .sui-medium
  .sui-medium-square
  .sui-y-combinator.sui-yc
  .sui-optin-monster
  .sui-opencart
  .sui-expeditedssl
  .sui-battery-4.sui-battery-full.sui-battery
  .sui-battery-3.sui-battery-three-quarters
  .sui-battery-2.sui-battery-half
  .sui-battery-1.sui-battery-quarter
  .sui-battery-0.sui-battery-empty
  .sui-mouse-pointer
  .sui-i-cursor
  .sui-object-group
  .sui-object-ungroup
  .sui-sticky-note
  .sui-sticky-note-o
  .sui-cc-jcb
  .sui-cc-diners-club
  .sui-clone
  .sui-balance-scale
  .sui-hourglass-o
  .sui-hourglass-1.sui-hourglass-start
  .sui-hourglass-2.sui-hourglass-half
  .sui-hourglass-3.sui-hourglass-end
  .sui-hourglass
  .sui-hand-grab-o.sui-hand-rock-o
  .sui-hand-paper-o.sui-hand-stop-o
  .sui-hand-scissors-o
  .sui-hand-lizard-o
  .sui-hand-spock-o
  .sui-hand-pointer-o
  .sui-hand-peace-o
  .sui-trademark
  .sui-registered
  .sui-creative-commons
  .sui-gg
  .sui-gg-circle
  .sui-tripadvisor
  .sui-odnoklassniki
  .sui-odnoklassniki-square
  .sui-get-pocket
  .sui-wikipedia-w
  .sui-safari
  .sui-chrome
  .sui-firefox
  .sui-opera
  .sui-internet-explorer
  .sui-television.sui-tv
  .sui-contao
  .sui-500px
  .sui-amazon
  .sui-calendar-plus-o
  .sui-calendar-minus-o
  .sui-calendar-times-o
  .sui-calendar-check-o
  .sui-industry
  .sui-map-pin
  .sui-map-signs
  .sui-map-o
  .sui-map
  .sui-commenting
  .sui-commenting-o
  .sui-houzz
  .sui-vimeo
  .sui-black-tie
  .sui-fonticons
  .sui-reddit-alien
  .sui-edge
  .sui-credit-card-alt
  .sui-codiepie
  .sui-modx
  .sui-fort-awesome
  .sui-usb
  .sui-product-hunt
  .sui-mixcloud
  .sui-scribd
  .sui-pause-circle
  .sui-pause-circle-o
  .sui-stop-circle
  .sui-stop-circle-o
  .sui-shopping-bag
  .sui-shopping-basket
  .sui-hashtag
  .sui-bluetooth
  .sui-bluetooth-b
  .sui-percent
  .sui-gitlab
  .sui-wpbeginner
  .sui-wpforms
  .sui-envira
  .sui-universal-access
  .sui-wheelchair-alt
  .sui-question-circle-o
  .sui-blind
  .sui-audio-description
  .sui-volume-control-phone
  .sui-braille
  .sui-assistive-listening-systems
  .sui-american-sign-language-interpreting.sui-asl-interpreting
  .sui-deaf.sui-deafness.sui-hard-of-hearing
  .sui-glide
  .sui-glide-g
  .sui-sign-language.sui-signing
  .sui-low-vision
  .sui-viadeo
  .sui-viadeo-square
  .sui-snapchat
  .sui-snapchat-ghost
  .sui-snapchat-square
  .sui-first-order
  .sui-yoast
  .sui-themeisle
  .sui-google-plus-circle.sui-google-plus-official
  .sui-fa.sui-font-awesome
  .sui-handshake-o
  .sui-envelope-open
  .sui-envelope-open-o
  .sui-linode
  .sui-address-book
  .sui-address-book-o
  .sui-address-card.sui-vcard
  .sui-address-card-o.sui-vcard-o
  .sui-user-circle
  .sui-user-circle-o
  .sui-user-o
  .sui-id-badge
  .sui-drivers-license.sui-id-card
  .sui-drivers-license-o.sui-id-card-o
  .sui-quora
  .sui-free-code-camp
  .sui-telegram
  .sui-thermometer-4.sui-thermometer-full.sui-thermometer
  .sui-thermometer-3.sui-thermometer-three-quarters
  .sui-thermometer-2.sui-thermometer-half
  .sui-thermometer-1.sui-thermometer-quarter
  .sui-thermometer-0.sui-thermometer-empty
  .sui-shower
  .sui-bath.sui-bathtub.sui-s15
  .sui-podcast
  .sui-window-maximize
  .sui-window-minimize
  .sui-window-restore
  .sui-times-rectangle
  .sui-window-close
  .sui-times-rectangle-o
  .sui-window-close-o
  .sui-bandcamp
  .sui-grav
  .sui-etsy
  .sui-imdb
  .sui-ravelry
  .sui-eercast
  .sui-microchip
  .sui-snowflake-o
  .sui-superpowers
  .sui-wpexplorer
  .sui-meetup
  .sui-mastodon
  .sui-mastodon-alt
  .sui-fork-awesome
  .sui-fork-circle
  .sui-peertube
  .sui-diaspora
  .sui-friendica
  .sui-gnu-social
  .sui-liberapay-square
  .sui-liberapay
  .sui-scuttlebutt
  .sui-ssb
  .sui-hubzilla
  .sui-social-home
  .sui-artstation
  .sui-xmpp
  .sui-archive-org
  .sui-freedombox
  .sui-tipeee
  .sui-react
  .sui-dogmazic
  .sui-zotero
  .sui-nodejs
  .sui-nextcloud
  .sui-nextcloud-square
  .sui-hackaday
  .sui-laravel
  .sui-signalapp";


  public function actionIndex(){
    if(Yii::$app->request->isAjax){
      return $this->renderAjax('index');
    }
  }

  public function actionRender(){
    if(Yii::$app->request->isAjax){
      $data = Yii::$app->request->post();
      $id = rand(1, 999).'qut'.rand(1, 999).'re'.rand(1, 999);
      return $this->renderPartial('qut-render', [
        'id' => $id,
        'data' => $data['obj']
      ]);
    }
  }
  public function actionIcon(){
    $icon = $this->array;
    return $this->renderPartial('icon',['icon' => $icon]);
  }

  public function actionUpdate(){
    if(Yii::$app->request->isAjax){
      $data = Yii::$app->request->post();
      return $this->renderPartial('qut-update', [
        'data' => $data['obj']
      ]);
    }
  }
}

